/* Cloudinary - secure document storage.
   Files are uploaded as type "authenticated": the delivery URL only works
   when it carries a valid signature generated by our server. The raw URL
   alone (if leaked) will not open the file. */
const { v2: cloudinary } = require("cloudinary");

cloudinary.config({
  cloud_name: process.env.CLOUDINARY_CLOUD_NAME,
  api_key: process.env.CLOUDINARY_API_KEY,
  api_secret: process.env.CLOUDINARY_API_SECRET,
  secure: true,
});

const FOLDER = "eduverify/documents";

/** Upload a file buffer to Cloudinary as an authenticated (signed) asset. */
function uploadBuffer(buffer, appNo, docCode) {
  return new Promise((resolve, reject) => {
    const stream = cloudinary.uploader.upload_stream(
      {
        folder: `${FOLDER}/${appNo}`,
        public_id: `${docCode}_${Date.now()}`,
        resource_type: "auto",
        type: "authenticated",
        overwrite: true,
      },
      (err, result) => (err ? reject(err) : resolve(result))
    );
    stream.end(buffer);
  });
}

/** Build a signed delivery URL for an authenticated asset. */
function signedUrl(doc, attachment = false) {
  if (!doc || !doc.file_public_id) return null;
  return cloudinary.url(doc.file_public_id, {
    type: "authenticated",
    resource_type: doc.file_resource_type || "image",
    format: doc.file_format || undefined,
    secure: true,
    sign_url: true,
    flags: attachment ? "attachment" : undefined,
  });
}

/** Fetch a stored document's bytes (used to build bulk-download ZIPs). */
async function fetchAssetBuffer(doc) {
  const url = signedUrl(doc, false);
  if (!url) return null;
  const resp = await fetch(url);
  if (!resp.ok) throw new Error(`fetch failed (${resp.status}) for ${doc.doc_code}`);
  return Buffer.from(await resp.arrayBuffer());
}

/** Permanently delete a stored file (used when a student re-uploads). */
async function destroyAsset(publicId, resourceType) {
  if (!publicId) return;
  try {
    await cloudinary.uploader.destroy(publicId, {
      resource_type: resourceType || "image",
      type: "authenticated",
    });
  } catch (e) {
    console.warn("Cloudinary delete failed:", e.message);
  }
}

function isConfigured() {
  return !!(
    process.env.CLOUDINARY_CLOUD_NAME &&
    process.env.CLOUDINARY_API_KEY &&
    process.env.CLOUDINARY_API_SECRET
  );
}

module.exports = { cloudinary, uploadBuffer, signedUrl, fetchAssetBuffer, destroyAsset, isConfigured };
